### ISSUE TITLE
Support for full logic in flags

### ISSUE THREAD

**Issue by JustinTervala** [nsacyber/WALKOFF#141]
Currently all flags on a nextstep must be evaluated as true for a step to proceed to that step. It would be beneficial to allow "or" logic, meaning that one set of flags or another set of flags must be satisfied to progress to another step.  A workaround is to create a new flag which includes this logic, but that is not a great solution. A good implementation could be challenging.

**Comment by shadowbq** [comment]
potentially subscribe full logic in the solution (AND, OR, XOR, NOT, NAND, NOR and XNOR)
