### ISSUE TITLE
Refactor API storage

### ISSUE THREAD

**Issue by JustinTervala** [nsacyber/WALKOFF#161]
Currently, the app API's are stored in a global object in core.config.config as a dict exactly as they are parsed from the app api yaml. This is not great practice and is one of the reasons the validation functions are messy. I propose that we Make an AppApi object and subsequent objects (like ActionApi which has FlagApi and FilterApi objects). This will make the validation functions easier to read, modify, and test.

**Comment by emrodas10** [comment]
Closing as this has been implemented.
