### ISSUE TITLE
Application @events do not appear to set Event.receivers

### ISSUE THREAD

**Issue by billmurrin** [nsacyber/WALKOFF#166]
Using the related tutorial and code found in the Utilities App, I'm implementing an application listener which is tied to an @event in my App for TheHive. The code is available [here](https://github.com/billmurrin/thehive-walkoff-app). TheHive is an open source SOC incident management tool ([more information](https://thehive-project.org/).

The issue I'm having is that when I do my event_action.trigger(data) method, it never executes the method that is decorated with @event(action_name) inside of my App. When I look at the Event.trigger method, I see it iterates the self.receivers for the class and then executes the function. If I add print statements to the Event.trigger method, I do not see any receivers being set for the object. Here is my event code.

**events.py**
```
from apps import Event, AppBlueprint
from flask import Blueprint, request

blueprint = AppBlueprint(blueprint=Blueprint('TheHiveEvents', __name__))

hive_event = Event('TheHiveWebHook')

@blueprint.blueprint.route('/thehive_webhook', methods=['POST'])
def thehive_webhook():
    data = request.get_json()
    print("Received data")
    print(data)
    hive_event.trigger(data)
    return 'Success'
```

When data is sent to the event uri above, I see the following output from the print statements I placed in the Event.trigger method:
```
In the trigger method
self receivers
set([])
```

Now, If I add `event_.connect(func)` to the _event method within the event decorator (core.decorators.py), the code will have a receiver set and I see the data get passed to @event decorated function in app.py.

Output with the addition of code to the _event method:
```
In the trigger method
self receivers
set([<function web_hook_handler at 0x7f6b2990e8c0>])
```

As I said, this code now gets passed to the decorated function in my App.
```
I'm in the handler. Here's the data
```

The other issue is that due to the calling of func within Event.trigger, I does not pass the object back into my App method `event_handler(self, data)` - it doesn't contain enough arguments. The send method within the wrapper function looks like it should be executing the function with the correct arguments, but that is never getting executed.

I'm not sure if there is a possible bug here, or if I am doing something incorrectly? Any help is appreciated.

**Comment by JustinTervala** [comment]
I was able to replicate the issue, and it does appear to be a bug. I'll take a look and include a patch in our upcoming release if possible.

**Comment by JustinTervala** [comment]
We were not able to hunt down a suitable fix for this bug. It had to do with the fact that apps are run in one process whereas the server runs in another process. We were testing this feature in a single process where it all worked as expected. The fix would involve some way of registering a callback in the server process and communicating the data to the workflow processes over ZeroMQ. 
However, we implemented a new way of constructing event-driven actions using generic triggers which use conditions to evaluate the incoming data. With this new release, we also made it possible for users to make their own conditions and transforms. 
I believe you should be able to refactor your actions and workflows to use triggers and conditions to achieve the same results. If you are not able to do so, we will on a feature which helps achieve your use case.

**Comment by billmurrin** [comment]
I guess my only concern is if the trigger/conditions require JWT in order to work? 

I am looking for a way to send data from a webhook into WALKOFF and start a workflow. The webhook does not, at least at this point, conduct any sort of the authentication; it basically just sends a JSON record to a given HTTP/HTTPS URL. The @event actions seemed like a pretty straightforward and well documented way to make a listener so that data can be sent into a workflow from an App.

I will try to refactor the code to use the triggers and conditions. I'll go check out the documentation and give it a go. I appreciate the follow-up. Thank you.

**Comment by coreyjrobins** [comment]
This functionality has since been removed.
