### ISSUE TITLE
Split up the App API JSON Schema into multiple files

### ISSUE THREAD

**Issue by JustinTervala** [nsacyber/WALKOFF#171]
Currently the App API JSON Schema in `data/walkoff_schema.json` is about 1000 lines long and is getting a bit bloated and hand to maintain. It would be better if it is split up into manageable files and placed in its own directory inside data. This should only involve using the `{"#ref" : "../path/to/new/file"}` feature of JSON schemas (see this issue here: https://github.com/Julian/jsonschema/issues/98). This may also involve a teak in `core.config.config` depending on the reference resolver being used and possibly a change to `core.config.paths` if the path to the schema changes.

**Comment by emrodas10** [comment]
Closing as codebase has diverged.
