### ISSUE TITLE
Add support for datetime and duration primitive types for actions

### ISSUE THREAD

**Issue by JustinTervala** [nsacyber/WALKOFF#172]
It would be helpful to have support for "datetime" and "duration" primitive types for action arguments. The api.yaml file entry might look something like this:
```
do this at a time:
  run: app.do_this_at_a_time
  parameters:
    - type: datetime
      description: The datetime to do the thing
      required: true
```
This would allow for special validators to check for valid parameters as well as modals in the UI to improve user experience

**Comment by emrodas10** [comment]
Closing as this has been implemented. Parameters now have JSON Schema support.
