### ISSUE TITLE
Allow Angular components as Interfaces

### ISSUE THREAD

**Issue by jps39** [nsacyber/WALKOFF#181]
Currently Interfaces are limited to relatively simple JS (or whatever plugin libraries are loaded by the interface). It would be very nice to be able to just add an additional component and somehow load it into the main module (or add in a new app module just for this), so interface developers can utilize Angular functionality to make writing interfaces easier (and better utilize our apis).

**Comment by emrodas10** [comment]
Closing as interfaces no longer exist. Codebase has diverged.
