### ISSUE TITLE
Develop user-friendly bash script to configure a Linux box with the WALKOFF pre-reqs in a user-friendly way

### ISSUE THREAD

**Issue by astrohart** [nsacyber/WALKOFF#216]
Wonder whether it would be worth while to enable end users to clone the repo and then run a bash script that runs ```apt-get install``` etc. to configure all the WALKOFF pre-reqs in such a user friendly fashion so that then setup_walkoff.py will just run.

**Comment by emrodas10** [comment]
Closing as bootloader handles everything now other than install of Docker CE, Docker Compose, and Git. The install processes for these are dependent on the platform/OS you are running so automating them wouldn't be worth it.
