### ISSUE TITLE
attaching to network failed - context deadline exceeded

### ISSUE THREAD

**Issue by BustedSec** [nsacyber/WALKOFF#225]
Below is the relevant section of the installation output. From what I can tell Postgres creation failed which causes other things to not work as expected. 
OS Info: Linux walkoff 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Status: Downloaded newer image for qoomon/docker-host:latest
Creating postgres              ... error
Creating walkoff_api_gateway_1 ...
Creating redis                 ...
Creating walkoff_dockerhost_1  ...
Creating walkoff_registry_1    ...
Creating walkoff_api_gateway_1 ... error
ERROR: for postgres  Cannot start service postgres: attaching to network failed, make sure your network options are correct and check manager logs: context deadline exceeded

ERROR: for walkoff_api_gateway_1  Cannot start service api_gateway: attaching to network failed, make sure your network options are correct and check manager loCreating walkoff_registry_1    ... error

ERROR: for walkoff_registry_1  Cannot start service registry: attaching to network failed, make sure your network options are correct and check manager logs: context deadline exceeded

ERROR: for redis  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for walkoff_dockerhost_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for api_gateway  Cannot start service api_gateway: attaching to network failed, make sure your network options are correct and check manager logs: context deadline exceeded

ERROR: for dockerhost  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for redis  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for postgres  Cannot start service postgres: attaching to network failed, make sure your network options are correct and check manager logs: context deadline exceeded

ERROR: for registry  Cannot start service registry: attaching to network failed, make sure your network options are correct and check manager logs: context deadline exceeded
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).

**Comment by adpham95** [comment]
From what I've seen this could be one of two things:

- An older version of Docker or Docker-Compose is installed. 
- Occasionally docker-compose or docker stack will not bring up the `walkoff_default` network. We don't exactly know what causes this yet, but re-running the command should ensure it comes up.

Let us know if it isn't one of those.

**Comment by BustedSec** [comment]
I have the latest version of docker and docker-compose installed. This is a fresh install after running apt-get update && apt-get upgrade -y. I tried deleting the folder, removing the node from the swarm, and re-cloning the repo. I tried installing again and get the following error message appended to several services "attaching to network failed, make sure your network options are correct and check manager logs: context deadline exceeded". Please advise, thank you

**Comment by BustedSec** [comment]
after running the command again I get  "network walkoff_default not found" errors. I'm kind of new to docker, how can I manually create this network?

**Comment by adpham95** [comment]
Sorry for leaving this hanging. I'm currently working on a "bootloader" container which might help alleviate setup issues by taking over from `docker stack deploy` and including other all of our other requirements. I'll update this issue once that's complete.

**Comment by ch40s** [comment]
I get the same error, any progress on this or way to resolve it?

**Comment by emrodas10** [comment]
@ch40s It appears that the errors you have been getting may have been resolved. Your most recent issues seem to be further along in the build process so I am closing this one.

**Comment by anselmobattisti** [comment]
In my case the problem was cause by the Docker installed via snap! 

The version was the same but something broke!

Removed it and install via APT
