### ISSUE TITLE
Cannot change admin default password

### ISSUE THREAD

**Issue by vedburtruba** [nsacyber/WALKOFF#228]
Hello!

I have installed Walkoff using guide from https://walkoff.readthedocs.io/en/latest/index.html

Walkoff seems to be running ok and I have access to its web interface.

But when I try to change admin password to non-default I receive the following error:
Http failure response for https://192.168.0.19:8080/api/users: 405 METHOD NOT ALLOWED

**Comment by adpham95** [comment]
Thanks for trying out Walkoff - this should be fixed by f5d0ebc which was pushed to the alpha branch, let us know if you run into any other issues.

**Comment by tjohnson-bah** [comment]
Tested this on 1.0.0-alpha and it's now working
