### ISSUE TITLE
The new walkoff bootloader isn't working

### ISSUE THREAD

**Issue by aoighost** [nsacyber/WALKOFF#231]
The new walkoff bootloader isn't working

.\walkoff.ps1 build
Creating walkoff_resource_registry_1 ... error

ERROR: for walkoff_resource_registry_1  Cannot start service resource_registry: Could not attach to network walkoff_default: rpc error: code = PermissionDenied desc = network walkoff_default not manually attachable

ERROR: for resource_registry  Cannot start service resource_registry: Could not attach to network walkoff_default: rpc error: code = PermissionDenied desc = network walkoff_default not manually attachable
ERROR: Encountered errors while bringing up the project.
Beginning build process.
Step 1/14 : FROM python:3.7.4-slim-buster as base
 ---> 63491ee411bb

Step 2/14 : FROM base as builder
 ---> 63491ee411bb
Step 3/14 : RUN apt-get update  && apt-get install -y --no-install-recommends git autoconf g++  && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 9c669437ebde
Step 4/14 : RUN mkdir /install
 ---> Using cache
 ---> 5b4075370f74
Step 5/14 : WORKDIR /install
 ---> Using cache
 ---> 9c5f6ab9228d
Step 6/14 : COPY ./app_sdk/requirements.txt /requirements.txt
 ---> Using cache
 ---> 38586fca074a
Step 7/14 : RUN pip install --no-warn-script-location --prefix="/install" git+https://github.com/aio-libs/aioredis.git
 ---> Using cache
 ---> 455b04e98670
Step 8/14 : RUN pip install --no-warn-script-location --prefix="/install" --no-deps asteval
 ---> Using cache
 ---> 3b6ee61e82d2
Step 9/14 : RUN pip install --no-warn-script-location --prefix="/install" -r /requirements.txt
 ---> Using cache
 ---> b9d7229b8588

Step 10/14 : FROM base
 ---> 63491ee411bb
Step 11/14 : COPY --from=builder /install /usr/local
 ---> Using cache
 ---> 3526152b81bf
Step 12/14 : COPY ./app_sdk/walkoff_app_sdk/__init__.py /app/walkoff_app_sdk/__init__.py
 ---> Using cache
 ---> 762ab51c8db0
Step 13/14 : COPY ./app_sdk/walkoff_app_sdk/app_base.py /app/walkoff_app_sdk/app_base.py
 ---> Using cache
 ---> 0d0183c64f5f
Step 14/14 : COPY ./app_sdk/walkoff_app_sdk/common /app/walkoff_app_sdk/common
 ---> Using cache
 ---> 8c1aff3ac6df

Successfully built 8c1aff3ac6df
Successfully tagged 127.0.0.1:5000/walkoff_app_sdk:latest
The push refers to repository [127.0.0.1:5000/walkoff_app_sdk]
ERROR: Get http://127.0.0.1:5000/v2/: dial tcp 127.0.0.1:5000: connect: connection refused
Step 1/13 : FROM python:3.7.4-slim-buster as base
 ---> 63491ee411bb

Step 2/13 : FROM base as builder
 ---> 63491ee411bb
Step 3/13 : RUN apt-get update  && apt-get install -y --no-install-recommends autoconf g++ python3.7-dev  && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> d9c695f264d0
Step 4/13 : RUN mkdir /install
 ---> Using cache
 ---> 8707eb093ab3
Step 5/13 : WORKDIR /install
 ---> Using cache
 ---> 3c431a6e65c8
Step 6/13 : COPY ./api_gateway/requirements.txt /requirements.txt
 ---> Using cache
 ---> e76f7e2bfcb7
Step 7/13 : RUN pip install --no-warn-script-location --prefix="/install" -r /requirements.txt
 ---> Using cache
 ---> 35abd710d52f

Step 8/13 : FROM base
 ---> 63491ee411bb
Step 9/13 : COPY --from=builder /install /usr/local
 ---> Using cache
 ---> 8bd8b0df8ac6
Step 10/13 : COPY ./common /app/common
 ---> Using cache
 ---> c2fa75206478
Step 11/13 : COPY ./api_gateway /app/api_gateway
 ---> Using cache
 ---> a3eefcbfdc79
Step 12/13 : WORKDIR /app
 ---> Using cache
 ---> 683266c5bc16
Step 13/13 : CMD gunicorn -k gevent -b 0.0.0.0:8080 api_gateway.server.app:app
 ---> Using cache
 ---> 332362ab6467

Successfully built 332362ab6467
Successfully tagged 127.0.0.1:5000/api_gateway:latest
Step 1/17 : FROM python:3.7.4-slim-buster as base
 ---> 63491ee411bb

Step 2/17 : FROM base as builder
 ---> 63491ee411bb
Step 3/17 : RUN apt-get update  && apt-get install -y --no-install-recommends git autoconf g++  && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 9c669437ebde
Step 4/17 : RUN mkdir /install
 ---> Using cache
 ---> 5b4075370f74
Step 5/17 : WORKDIR /install
 ---> Using cache
 ---> 9c5f6ab9228d
Step 6/17 : COPY ./umpire/requirements.txt /requirements.txt
 ---> Using cache
 ---> a95c42a4cf46
Step 7/17 : RUN pip install --no-warn-script-location --prefix="/install" git+https://github.com/aio-libs/aioredis.git
 ---> Using cache
 ---> c0415e812ebd
Step 8/17 : RUN pip install --no-warn-script-location --prefix="/install" --no-deps asteval
 ---> Using cache
 ---> eca7cc02a19b
Step 9/17 : RUN pip install --no-warn-script-location --prefix="/install" -r /requirements.txt
 ---> Using cache
 ---> f03db3e007d6

Step 10/17 : FROM base
 ---> 63491ee411bb
Step 11/17 : COPY --from=builder /install /usr/local
 ---> Using cache
 ---> 641418a65290
Step 12/17 : COPY ./app_sdk /app/app_sdk
 ---> Using cache
 ---> 06b33fbb082e
Step 13/17 : COPY ./worker /app/worker
 ---> Using cache
 ---> 4fc87ec50f6e
Step 14/17 : COPY ./common /app/common
 ---> Using cache
 ---> 93ffacdef71f
Step 15/17 : COPY ./umpire /app/umpire
 ---> Using cache
 ---> f969911a90a0
Step 16/17 : WORKDIR /app
 ---> Using cache
 ---> ef3b00380623
Step 17/17 : CMD python -m umpire.umpire
 ---> Using cache
 ---> d40bdad15142

Successfully built d40bdad15142
Successfully tagged 127.0.0.1:5000/umpire:latest
Step 1/15 : FROM python:3.7.4-slim-buster as base
 ---> 63491ee411bb

Step 2/15 : FROM base as builder
 ---> 63491ee411bb
Step 3/15 : RUN apt-get update  && apt-get install -y --no-install-recommends git autoconf g++  && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 9c669437ebde
Step 4/15 : RUN mkdir /install
 ---> Using cache
 ---> 5b4075370f74
Step 5/15 : WORKDIR /install
 ---> Using cache
 ---> 9c5f6ab9228d
Step 6/15 : COPY ./worker/requirements.txt /requirements.txt
 ---> Using cache
 ---> 46f264e81da2
Step 7/15 : RUN pip install --no-warn-script-location --prefix="/install" git+https://github.com/aio-libs/aioredis.git
 ---> Using cache
 ---> 66556f941191
Step 8/15 : RUN pip install --no-warn-script-location --prefix="/install" --no-deps asteval
 ---> Using cache
 ---> d0c0e347806e
Step 9/15 : RUN pip install --no-warn-script-location --prefix="/install" -r /requirements.txt
 ---> Using cache
 ---> a0580ac957bf

Step 10/15 : FROM base
 ---> 63491ee411bb
Step 11/15 : COPY --from=builder /install /usr/local
 ---> Using cache
 ---> 1e5bd545edbe
Step 12/15 : COPY ./common /app/common
 ---> Using cache
 ---> 76f13c9562ad
Step 13/15 : COPY ./worker /app/worker
 ---> Using cache
 ---> 2725587d4bc0
Step 14/15 : WORKDIR /app
 ---> Using cache
 ---> 0590316647bf
Step 15/15 : CMD python -m worker.worker
 ---> Using cache
 ---> 651825a8acb4

Successfully built 651825a8acb4
Successfully tagged 127.0.0.1:5000/worker:latest
Step 1/11 : FROM 127.0.0.1:5000/walkoff_app_sdk as base
 ---> 8c1aff3ac6df

Step 2/11 : FROM base as builder
 ---> 8c1aff3ac6df
Step 3/11 : RUN mkdir /install
 ---> Using cache
 ---> ad2dd2457ed7
Step 4/11 : WORKDIR /install
 ---> Using cache
 ---> d27739b5ddca
Step 5/11 : COPY requirements.txt /requirements.txt
 ---> Using cache
 ---> c5b3389a2057
Step 6/11 : RUN pip install --no-warn-script-location --prefix="/install" -r /requirements.txt
 ---> Using cache
 ---> d0f88df274d3

Step 7/11 : FROM base
 ---> 8c1aff3ac6df
Step 8/11 : COPY --from=builder /install /usr/local
 ---> Using cache
 ---> 5fcba2053da8
Step 9/11 : COPY src /app
 ---> Using cache
 ---> e5a77c0758e5
Step 10/11 : WORKDIR /app
 ---> Using cache
 ---> 452e91a1e133
Step 11/11 : CMD python app.py --log-level DEBUG
 ---> Using cache
 ---> e634ea433643

Successfully built e634ea433643
Successfully tagged 127.0.0.1:5000/walkoff_app_hello_world:1.0.0
Step 1/11 : FROM 127.0.0.1:5000/walkoff_app_sdk as base
 ---> 8c1aff3ac6df

Step 2/11 : FROM base as builder
 ---> 8c1aff3ac6df
Step 3/11 : RUN mkdir /install
 ---> Using cache
 ---> ad2dd2457ed7
Step 4/11 : WORKDIR /install
 ---> Using cache
 ---> d27739b5ddca
Step 5/11 : COPY requirements.txt /requirements.txt
 ---> Using cache
 ---> 6abbc127b259
Step 6/11 : RUN pip install --no-warn-script-location --prefix="/install" -r /requirements.txt
 ---> Using cache
 ---> c1370a741b71

Step 7/11 : FROM base
 ---> 8c1aff3ac6df
Step 8/11 : COPY --from=builder /install /usr/local
 ---> Using cache
 ---> 1d8a627a5ef0
Step 9/11 : COPY src /app
 ---> Using cache
 ---> d9ca8cb553ec
Step 10/11 : WORKDIR /app
 ---> Using cache
 ---> a08d045e91bb
Step 11/11 : CMD python app.py --log-level DEBUG
 ---> Using cache
 ---> feb994e196be

Successfully built feb994e196be
Successfully tagged 127.0.0.1:5000/walkoff_app_hive:1.0.0
Step 1/11 : FROM 127.0.0.1:5000/walkoff_app_sdk as base
 ---> 8c1aff3ac6df

Step 2/11 : FROM base as builder
 ---> 8c1aff3ac6df
Step 3/11 : RUN mkdir /install
 ---> Using cache
 ---> ad2dd2457ed7
Step 4/11 : WORKDIR /install
 ---> Using cache
 ---> d27739b5ddca
Step 5/11 : COPY requirements.txt /requirements.txt
 ---> Using cache
 ---> 7051082ad6da
Step 6/11 : RUN pip install --no-warn-script-location --prefix="/install" -r /requirements.txt
 ---> Using cache
 ---> 698b2e056221

Step 7/11 : FROM base
 ---> 8c1aff3ac6df
Step 8/11 : COPY --from=builder /install /usr/local
 ---> Using cache
 ---> 9a357c67fd8c
Step 9/11 : COPY src /app
 ---> Using cache
 ---> a92c51a73243
Step 10/11 : WORKDIR /app
 ---> Using cache
 ---> bc6852a650f0
Step 11/11 : CMD python app.py --log-level DEBUG
 ---> Using cache
 ---> 0828a1253bb1

Successfully built 0828a1253bb1
Successfully tagged 127.0.0.1:5000/walkoff_app_ip_addr_utils:1.0.0
Step 1/12 : FROM 127.0.0.1:5000/walkoff_app_sdk as base
 ---> 8c1aff3ac6df

Step 2/12 : FROM base as builder
 ---> 8c1aff3ac6df
Step 3/12 : RUN mkdir /install
 ---> Using cache
 ---> ad2dd2457ed7
Step 4/12 : WORKDIR /install
 ---> Using cache
 ---> d27739b5ddca
Step 5/12 : COPY requirements.txt /requirements.txt
 ---> Using cache
 ---> 3149cc7e8662
Step 6/12 : RUN pip install --no-warn-script-location --prefix="/install" -r /requirements.txt
 ---> Using cache
 ---> 23b4f89446cd

Step 7/12 : FROM base
 ---> 8c1aff3ac6df
Step 8/12 : COPY --from=builder /install /usr/local
 ---> Using cache
 ---> fc4b6ba54ff0
Step 9/12 : COPY src /app
 ---> Using cache
 ---> 89247d4838b7
Step 10/12 : RUN apt-get update  && apt-get install -y --no-install-recommends nmap  && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> b71bd75f4af7
Step 11/12 : WORKDIR /app
 ---> Using cache
 ---> 7cb05b65144b
Step 12/12 : CMD python app.py --log-level DEBUG
 ---> Using cache
 ---> 6c391938069a

Successfully built 6c391938069a
Successfully tagged 127.0.0.1:5000/walkoff_app_nmap:1.0.0
Step 1/11 : FROM 127.0.0.1:5000/walkoff_app_sdk as base
 ---> 8c1aff3ac6df

Step 2/11 : FROM base as builder
 ---> 8c1aff3ac6df
Step 3/11 : RUN mkdir /install
 ---> Using cache
 ---> ad2dd2457ed7
Step 4/11 : WORKDIR /install
 ---> Using cache
 ---> d27739b5ddca
Step 5/11 : COPY requirements.txt /requirements.txt
 ---> Using cache
 ---> 7051082ad6da
Step 6/11 : RUN pip install --no-warn-script-location --prefix="/install" -r /requirements.txt
 ---> Using cache
 ---> 698b2e056221

Step 7/11 : FROM base
 ---> 8c1aff3ac6df
Step 8/11 : COPY --from=builder /install /usr/local
 ---> Using cache
 ---> 9a357c67fd8c
Step 9/11 : COPY src /app
 ---> Using cache
 ---> f5dcd208a497
Step 10/11 : WORKDIR /app
 ---> Using cache
 ---> 16179a16f4ad
Step 11/11 : CMD python app.py --log-level DEBUG
 ---> Using cache
 ---> a2d8d8c0b98a

Successfully built a2d8d8c0b98a
Successfully tagged 127.0.0.1:5000/walkoff_app_power_shell:1.0.0
Step 1/14 : FROM python:3.7.4-slim-buster as base
 ---> 63491ee411bb

Step 2/14 : FROM base as builder
 ---> 63491ee411bb
Step 3/14 : RUN apt-get update  && apt-get install -y --no-install-recommends git autoconf g++  && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 9c669437ebde
Step 4/14 : RUN mkdir /install
 ---> Using cache
 ---> 5b4075370f74
Step 5/14 : WORKDIR /install
 ---> Using cache
 ---> 9c5f6ab9228d
Step 6/14 : COPY ./app_sdk/requirements.txt /requirements.txt
 ---> Using cache
 ---> 38586fca074a
Step 7/14 : RUN pip install --no-warn-script-location --prefix="/install" git+https://github.com/aio-libs/aioredis.git
 ---> Using cache
 ---> 455b04e98670
Step 8/14 : RUN pip install --no-warn-script-location --prefix="/install" --no-deps asteval
 ---> Using cache
 ---> 3b6ee61e82d2
Step 9/14 : RUN pip install --no-warn-script-location --prefix="/install" -r /requirements.txt
 ---> Using cache
 ---> b9d7229b8588

Step 10/14 : FROM base
 ---> 63491ee411bb
Step 11/14 : COPY --from=builder /install /usr/local
 ---> Using cache
 ---> 3526152b81bf
Step 12/14 : COPY ./app_sdk/walkoff_app_sdk/__init__.py /app/walkoff_app_sdk/__init__.py
 ---> Using cache
 ---> 762ab51c8db0
Step 13/14 : COPY ./app_sdk/walkoff_app_sdk/app_base.py /app/walkoff_app_sdk/app_base.py
 ---> Using cache
 ---> 0d0183c64f5f
Step 14/14 : COPY ./app_sdk/walkoff_app_sdk/common /app/walkoff_app_sdk/common
 ---> Using cache
 ---> 8c1aff3ac6df

Successfully built 8c1aff3ac6df
Successfully tagged 127.0.0.1:5000/walkoff_app_sdk:latest
Step 1/11 : FROM 127.0.0.1:5000/walkoff_app_sdk as base
 ---> 8c1aff3ac6df

Step 2/11 : FROM base as builder
 ---> 8c1aff3ac6df
Step 3/11 : RUN mkdir /install
 ---> Using cache
 ---> ad2dd2457ed7
Step 4/11 : WORKDIR /install
 ---> Using cache
 ---> d27739b5ddca
Step 5/11 : COPY requirements.txt /requirements.txt
 ---> Using cache
 ---> 4fb99aaa5d48
Step 6/11 : RUN pip install --no-warn-script-location --prefix="/install" -r /requirements.txt
 ---> Using cache
 ---> 2634817bfecd

Step 7/11 : FROM base
 ---> 8c1aff3ac6df
Step 8/11 : COPY --from=builder /install /usr/local
 ---> Using cache
 ---> 391bf90cb5c9
Step 9/11 : COPY src /app
 ---> Using cache
 ---> 621f07a6a59e
Step 10/11 : WORKDIR /app
 ---> Using cache
 ---> 7d78d62d9748
Step 11/11 : CMD python app.py --log-level DEBUG
 ---> Using cache
 ---> 9dcf4866e0ad

Successfully built 9dcf4866e0ad
Successfully tagged 127.0.0.1:5000/walkoff_app_ssh:1.0.0
Step 1/11 : FROM 127.0.0.1:5000/walkoff_app_sdk as base
 ---> 8c1aff3ac6df

Step 2/11 : FROM base as builder
 ---> 8c1aff3ac6df
Step 3/11 : RUN mkdir /install
 ---> Using cache
 ---> ad2dd2457ed7
Step 4/11 : WORKDIR /install
 ---> Using cache
 ---> d27739b5ddca
Step 5/11 : COPY requirements.txt /requirements.txt
 ---> Using cache
 ---> c77b692d8b86
Step 6/11 : RUN pip install --no-warn-script-location --prefix="/install" -r /requirements.txt
 ---> Using cache
 ---> a189fad5dd3d

Step 7/11 : FROM base
 ---> 8c1aff3ac6df
Step 8/11 : COPY --from=builder /install /usr/local
 ---> Using cache
 ---> 5fcba2053da8
Step 9/11 : COPY src /app
 ---> Using cache
 ---> e44655cbffe6
Step 10/11 : WORKDIR /app
 ---> Using cache
 ---> 3df6472af277
Step 11/11 : CMD python app.py --log-level DEBUG
 ---> Using cache
 ---> 88c37cd95f6e

Successfully built 88c37cd95f6e
Successfully tagged 127.0.0.1:5000/walkoff_app_walk_off:1.0.0
The push refers to repository [127.0.0.1:5000/api_gateway]
ERROR: Get http://127.0.0.1:5000/v2/: dial tcp 127.0.0.1:5000: connect: connection refused
Removing walkoff_resource_registry_1 ... done
PS C:\Users\aoighost\Desktop\motokodev\WALKOFF>

PS C:\Users\aoighost\Desktop\motokodev\WALKOFF> .\walkoff.ps1 up
Deploying Walkoff stack...
Ignoring unsupported options: build

Creating service walkoff_resource_portainer
failed to create service walkoff_resource_portainer: Error response from daemon: Mount denied:
The source path "C:/Users/aoighost/Desktop/motokodev/WALKOFF/data/portainer"
doesn't exist and is not known to Docker

Watching WALKOFF services (Ctrl+C to quit):

ID           NAME                      MODE       REPLICAS IMAGE                                          PORTS
--           ----                      ----       -------- -----                                          -----
x9y4kgvxib3l walkoff_api_gateway       replicated 1/1      127.0.0.1:5000/api_gateway:latest
qh9oqapi5j02 walkoff_app_hive          replicated 0/0      127.0.0.1:5000/walkoff_app_hive:1.0.0
kgyqmpyrehez walkoff_app_ip_addr_utils replicated 0/0      127.0.0.1:5000/walkoff_app_ip_addr_utils:1.0.0
k6yndshj80gp walkoff_app_nmap          replicated 0/0      127.0.0.1:5000/walkoff_app_nmap:1.0.0
ta43gnvwwh3u walkoff_app_sdk           replicated 0/0      127.0.0.1:5000/walkoff_app_sdk:latest
akcosyybv0a7 walkoff_app_ssh           replicated 0/0      127.0.0.1:5000/walkoff_app_ssh:1.0.0
8gcd91p824c5 walkoff_app_walk_off      replicated 0/0      127.0.0.1:5000/walkoff_app_walk_off:1.0.0
prd4ewuzq8rb walkoff_core_api_gateway  replicated 1/1      127.0.0.1:5000/api_gateway:latest
kwzksn5hx1wo walkoff_core_umpire       replicated 0/1      127.0.0.1:5000/umpire:latest
fj4sj5xkytjk walkoff_nginx             replicated 0/1      bitnami/nginx:latest                           *:8080-808...
m1yenhng2kgc walkoff_portainer         replicated 1/1      portainer/portainer:latest
z2hnxblh7x87 walkoff_postgres          replicated 1/1      postgres:latest
7yzefg610kbv walkoff_registry          replicated 0/1      registry:2                                     *:5000->50...
jxxb0dyw87lo walkoff_resource_postgres replicated 1/1      postgres:latest
rq8t4v6yg6c6 walkoff_umpire            replicated 0/1      127.0.0.1:5000/umpire:latest
r1ukxl8rln6w walkoff_walkoff_redis     replicated 1/1      redis:latest

**Comment by aoighost** [comment]
Note port 5000 and 8080 are clear according to powershell. Seems to be a continuation of previous issues.

**Comment by adpham95** [comment]
I noticed `r1ukxl8rln6w walkoff_walkoff_redis replicated 1/1 redis:latest` is still in your service listing. 

In the latest version that is called `walkoff_resource_redis` instead of `walkoff_walkoff_redis`. Seems like an older Walkoff stack is still running, which would also explain why you got `Could not attach to network walkoff_default: rpc error: code = PermissionDenied desc = network walkoff_default not manually attachable` at the very beginning, as that `attachable` flag was added recently.

I'm not sure why a docker system prune wouldn't get rid of it, but just to be sure, could you make sure that all the older stacks are removed (`docker stack rm walkoff`) and that there are no lingering services (`docker service ls`), networks (`docker network ls`) or containers (`docker ps`) that are related to the older versions?

**Comment by aoighost** [comment]
Removing walkoff_resource_registry_1 ... done
PS C:\Users\aoighost\Desktop\motokodev\WALKOFF> .\walkoff.ps1 up
Deploying Walkoff stack...
Ignoring unsupported options: build

Updating service walkoff_app_nmap (id: pxf6k0cu5mqn1wgjlwmsvmha2)
Creating service walkoff_core_umpire
Creating service walkoff_app_power_shell
Creating service walkoff_resource_portainer
failed to create service walkoff_resource_portainer: Error response from daemon: Mount denied:
The source path "C:/Users/aoighost/Desktop/motokodev/WALKOFF/data/portainer"
doesn't exist and is not known to Docker

got this. manually creating the folder fixed that but should be handled by the script

**Comment by aoighost** [comment]
Correction, now umpire isn't running, no workers are replicated, and none of the apps are available


ID           NAME                       MODE       REPLICAS IMAGE                                          PORTS
--           ----                       ----       -------- -----                                          -----
kizyial3bffk walkoff_app_hello_world    replicated 0/0      127.0.0.1:5000/walkoff_app_hello_world:1.0.0
rrhf93z6a3ij walkoff_app_hive           replicated 0/0      127.0.0.1:5000/walkoff_app_hive:1.0.0
o9jiomou2wip walkoff_app_ip_addr_utils  replicated 0/0      127.0.0.1:5000/walkoff_app_ip_addr_utils:1.0.0
pxf6k0cu5mqn walkoff_app_nmap           replicated 0/0      127.0.0.1:5000/walkoff_app_nmap:1.0.0
pxizposynr9e walkoff_app_power_shell    replicated 0/0      127.0.0.1:5000/walkoff_app_power_shell:1.0.0
p3yze6a8tg7t walkoff_app_sdk            replicated 0/0      127.0.0.1:5000/walkoff_app_sdk:latest
0d8hycmnpvqv walkoff_app_ssh            replicated 0/0      127.0.0.1:5000/walkoff_app_ssh:1.0.0
59qvsxv8av3g walkoff_app_walk_off       replicated 0/0      127.0.0.1:5000/walkoff_app_walk_off:1.0.0
56tcryb0c3sd walkoff_core_api_gateway   replicated 1/1      127.0.0.1:5000/api_gateway:latest
ysrcuqysont4 walkoff_core_umpire        replicated 0/1      127.0.0.1:5000/umpire:latest
clisa5pubkhl walkoff_core_worker        replicated 0/0      127.0.0.1:5000/worker:latest
50k7zejss6i2 walkoff_resource_nginx     replicated 1/1      bitnami/nginx:latest                           *:8080->8...
nhn5us8akqbe walkoff_resource_portainer replicated 1/1      portainer/portainer:latest
nygx39gajxkk walkoff_resource_postgres  replicated 1/1      postgres:latest
oi6rju2moezt walkoff_resource_redis     replicated 1/1      redis:latest
exjprz38vun4 walkoff_resource_registry  replicated 0/1      registry:2                                     *:5000->5...

**Comment by aoighost** [comment]
If I had to venture a guess it looks like the minio commit broke windows

**Comment by aoighost** [comment]
Linux walkoff.sh worked for a while but stopped working

aoighost@nomad:~/walkoff-motoko$ ./walkoff.sh up
Starting Walkoff Bootloader...
2019-07-24 20:40:01,913 - UMPIRE - DEBUG:Connected to Docker Engine: v18.09.7
2019-07-24 20:40:01,915 - BOOTLOADER - INFO:Skipping secret walkoff_encryption_key creation, it already exists.
2019-07-24 20:40:01,915 - BOOTLOADER - INFO:Creating persistent directories for registry, postgres, portainer...
2019-07-24 20:40:01,916 - BOOTLOADER - INFO:Deploying base services (registry, postgres, portainer, redis)...
2019-07-24 20:40:04,992 - BOOTLOADER - INFO:Updating service walkoff_resource_postgres (id: w5lirqbnyvcymrsr35mkfk3p4)
2019-07-24 20:40:04,993 - BOOTLOADER - INFO:Updating service walkoff_resource_redis (id: qqyjq2pgnczww6lz73akdppij)
2019-07-24 20:40:04,993 - BOOTLOADER - INFO:Updating service walkoff_resource_registry (id: l1g8cmrhxgdh8rmeh06ovwmji)
2019-07-24 20:40:04,993 - BOOTLOADER - INFO:Updating service walkoff_resource_minio (id: nozur0j0w0uktt84vhhec1jp8)
2019-07-24 20:40:04,993 - BOOTLOADER - INFO:Updating service walkoff_resource_portainer (id: 8jsnfj7arh9dey1ybh0t18dmt)
2019-07-24 20:40:05,286 - BOOTLOADER - INFO:Generated compose for hive version: 1.0.0
2019-07-24 20:40:05,287 - BOOTLOADER - INFO:Generated compose for ip_addr_utils version: 1.0.0
2019-07-24 20:40:05,287 - BOOTLOADER - INFO:Generated compose for nmap version: 1.0.0
2019-07-24 20:40:05,287 - BOOTLOADER - INFO:Generated compose for ssh version: 1.0.0
2019-07-24 20:40:05,288 - BOOTLOADER - INFO:Generated compose for hello_world version: 1.0.0
2019-07-24 20:40:05,288 - BOOTLOADER - INFO:Generated compose for power_shell version: 1.0.0
2019-07-24 20:40:05,289 - BOOTLOADER - INFO:Generated compose for walk_off version: 1.0.0
2019-07-24 20:40:05,326 - BOOTLOADER - INFO:Deploying Walkoff stack...
2019-07-24 20:40:06,493 - BOOTLOADER - INFO:Updating service walkoff_app_ip_addr_utils (id: ae70emx9s8xjpvj4lnhzqrcj7)
2019-07-24 20:40:06,493 - BOOTLOADER - INFO:Updating service walkoff_app_nmap (id: l0v773a0slnq3llplned9yq0a)
2019-07-24 20:40:06,493 - BOOTLOADER - INFO:Updating service walkoff_core_worker (id: vkysrxmyis28vv0iweho813qq)
2019-07-24 20:40:06,494 - BOOTLOADER - INFO:Updating service walkoff_core_api_gateway (id: 955z77n0orudagsbay9r56yfh)
2019-07-24 20:40:06,494 - BOOTLOADER - INFO:Updating service walkoff_app_hello_world (id: rx0q3ma75or5il5u3kf83ru21)
2019-07-24 20:40:06,494 - BOOTLOADER - INFO:Updating service walkoff_app_power_shell (id: i6kadd1rn6wmxatnf10zmng6w)
2019-07-24 20:40:06,494 - BOOTLOADER - INFO:Updating service walkoff_core_umpire (id: 3zq85jt38j8m39l0mfsgabpvk)
2019-07-24 20:40:06,494 - BOOTLOADER - INFO:Updating service walkoff_app_sdk (id: k7nb6s4evryztcgt46gbr66cq)
2019-07-24 20:40:06,494 - BOOTLOADER - INFO:Updating service walkoff_app_hive (id: ttnrzr0vbq867l9qmix4e8fjg)
2019-07-24 20:40:06,494 - BOOTLOADER - INFO:Updating service walkoff_resource_nginx (id: 3asjf6nnqvfbazyn8iq48hqvn)
2019-07-24 20:40:06,494 - BOOTLOADER - INFO:Updating service walkoff_app_walk_off (id: kamkldwqgzlfa6pjf4yr9sgra)
2019-07-24 20:40:06,494 - BOOTLOADER - INFO:Updating service walkoff_app_ssh (id: x10slm9yjwrevn77zdhii9ydl)
2019-07-24 20:40:06,495 - UMPIRE - INFO:Docker connection closed.

**Comment by aoighost** [comment]
ok I'm an idiot, linux works just fine, windows is still borked though

**Comment by adpham95** [comment]
Updated the Windows bootloader and stack YAML to match the Linux version. Let me know if you run into further issues.

**Comment by aoighost** [comment]
Still having issues.

.\walkoff.ps1 up
Deploying Walkoff stack...
Ignoring unsupported options: build

failed to update config walkoff_common_env.yml: Error response from daemon: rpc error: code = InvalidArgument desc = only updates to Labels are allowed
Some services may take some time to be ready. Use .\walkoff.ps1 status to check on them.

**Comment by aoighost** [comment]
It works, thanks
