### ISSUE TITLE
Global not saving

### ISSUE THREAD

**Issue by asucrews** [nsacyber/WALKOFF#260]
Hello,

Fresh Git clone, fresh ubuntu 18.04 vm, when trying to create new global variables i get the below errors.

10.0.0.2 - - [28/Feb/2020:21:34:14 +0000] "POST /walkoff/api/globals/ HTTP/1.1" 422 100 "https://192.168.10.32:8080/walkoff/settings/globals" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36"

INFO:     10.0.1.3:46446 - "POST /walkoff/api/globals/ HTTP/1.0" 422 Unprocessable Entity

**Comment by austinnichols101** [comment]
Same here.
