### ISSUE TITLE
Properly segregated testing environment

### ISSUE THREAD

**Issue by JustinTervala** [nsacyber/WALKOFF#86]
Currently some tests still rely on the apps module and the data module. This dependence on user-data should be removed and mocked in the tests module. This could involve making a testing configuration file and loading that as well as creating two base classes for test cases, one which is used for non-server tests and one which is used for server tests.

**Comment by shadowbq** [comment]
related to #87

**Comment by emrodas10** [comment]
Closing due to the codebase diverging. Need to evaluate testing priorities.
